### ISSUE TITLE
<model>.verify is not a function\n

### ISSUE THREAD

**Issue by yogieputra8** [strongloop/loopback-example-user-management#32] opened 2016-03-09 18:43 UTC
So, I try to make a model, called user-basic which bases on built-in model User.
Here's the user-basic.json:
```
{
  "name": "user-basic", 
  "base": "User",
  "idInjection": true, 
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "accessType": "READ",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

Here's the user-basic.js
```
var config = require('../../server/config.json');
var path = require('path');


module.exports = function(UserBasic) {
          UserBasic.afterRemote('create', function(ctx, member, next) {
            console.log('> user.afterRemote triggered');
            var options = {
              type: 'email',
              to: UserBasic.email,
              from: 'noreply@loopback.com',
              subject: 'Thanks for registering.',
              template: path.resolve(__dirname, '../../server/views/verify.ejs'),
              redirect: '/verified',
              user: UserBasic
            };
            UserBasic.verify(options, function(err) {
              console.log('aaaaa', member.location, err);
              if (err) {
                next(err);
              } else {
                next();
              }
            });

          });

          //send password reset link when requested
          UserBasic.on('resetPasswordRequest', function(info) {
            var url = 'http://' + config.host + ':' + config.port + '/reset-password';
            var html = 'Click <a href="' + url + '?access_token=' +
              info.accessToken.id + '">here</a> to reset your password';

            UserBasic.app.models.Email.send({
              to: info.email,
              from: info.email,
              subject: 'Password reset',
              html: html
            }, function(err) {
              if (err) return console.log('> error sending password reset email');
              console.log('> sending password reset email to:', info.email);
            });
          });
        };
```

In DataSource, I am using Cloudant (couchDB), here it is:

```
{
  "db": {
    "name": "db",
    "connector": "memory"
  }, 
  "cloudant-pop": {
    "host": "userxxx.cloudant.com",
    "port": 443,
    "url": "https://userxxx.com",
    "database": "population",
    "password": "userxxx",
    "name": "cloudant-pop",
    "connector": "couch",
    "db": "population",
    "protocol": "https",
    "auth": {
      "admin": {
       "username": "userxxx",
        "password": "userxxx"
      },
      "reader": {
        "username": "userxxx",
        "password": "userxxx"
      },
      "writer": {
        "username": "userxxx",
        "password": "userxxx"
      }
    },
    "user": "userxxx"
  }, 
  "emailDs": {
    "name": "emailDs",
    "connector": "mail",
    "transports": [
      {
        "type": "smtp",
        "host": "smtp.gmail.com",
        "secure": true,
        "port": 465,
        "tls": {
          "rejectUnauthorized": false
        },
        "auth": {
          "user": "aaa@gmail.com",
          "pass": "aaa"
        }
      }
    ]
  }
}
```

This is my model-config.json, Since I want to store the user credential to my Cloudant DB so I connect my user-basic model to my Cloudant Datasource:
```
"user-basic": {
    "dataSource": "cloudant-pop",
    "public": true,
    "options": {
      "emailVerificationRequired": true
    }
  }
```

I ran the server and try POST a new user via [http://0.0.0.0:3008/explorer](url). It gives me an error: 
```
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "UserBasic.verify is not a function",
    "stack": "TypeError: UserBasic.verify is not a function\n    at /Users/yogieputra/Desktop/backend_powercube/common/models/user-basic.js:23:23\n    at Function.<anonymous> (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback/lib/model.js:207:11)\n    at execStack (/Users/yogieputra/Desktop/backend_powercube/node_modules/strong-remoting/lib/remote-objects.js:480:26)\n    at RemoteObjects.execHooks (/Users/yogieputra/Desktop/backend_powercube/node_modules/strong-remoting/lib/remote-objects.js:492:10)\n    at phaseAfterInvoke (/Users/yogieputra/Desktop/backend_powercube/node_modules/strong-remoting/lib/remote-objects.js:652:10)\n    at runHandler (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback-phase/lib/phase.js:130:5)\n    at iterate (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)\n    at runHandlers (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback-phase/lib/phase.js:139:13)\n    at iterate (/Users/yogieputra/Desktop/backend_powercube/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)"
  }
}
```
When I check the Database, I got the user data that I've been POST recently.
Can you guys tell me what I've been missing?
Please help

**Comment by richardpringle** [comment] 2016-04-01 15:52
Hey @yogieputra8, sorry about the delayed response, the best place to ask questions and get a more timely answer are as follows:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

But let me try to help you out.

It's always a good idea to keep the [API docs](https://apidocs.strongloop.com/loopback/#user-prototype-verify) open when you're working with any of the examples (I had to go look at them because what you were doing looked right to me too). From the docs, you can see that `verify` is an instance method. In your case, `member` is the user instance. 

Replace `UserBasic.verify` with `member.verify` and everything should work as expected.

Also, one of the best ways to get help with LoopBack is to fork the [LoopBack-sanbox](https://github.com/strongloop/loopback-sandbox) and reproduce your issue in the fork. Instead of having to copy paste all that code, you can just say "here is my sandbox" and whoever is helping you can go take a quick look, make some modifications, and tell you exactly what you need to do.

Hope that helps.

Good luck and happy coding!

**Comment by richardpringle** [comment] 2016-04-01 18:17
Closing the issue since it is a question, but please feel free to carry on the discussion with me in here. Just make sure that you mention me directly in your comments.

**Closed by richardpringle** 2016-04-01 18:17 UTC
Labels: question
