### ISSUE TITLE
user.afterRemote('create, ...)` not firing

### ISSUE THREAD

**Issue by talpasco** [strongloop/loopback-example-user-management#34] opened 2016-03-28 12:57 UTC
I'm wondering if I'm the only one.
In my case, user.afterRemote('create, ...)` isn't firing after signing up (using this repo).

While looking for a solution, I've found this outdated version of it: "https://github.com/dstroot/loopback-faq-user-management" and it works like a charm.

Wondering why is that...

**Comment by talpasco** [comment] 2016-03-28 15:27
This is probably also relevant for: https://github.com/strongloop/loopback-example-passport/issues/42#issuecomment-202402133

**Comment by richardpringle** [comment] 2016-03-28 15:41
@talpasco, yeah I just downloaded the latest code and signup works fine. The remote hook is triggered and everything.

**Comment by richardpringle** [comment] 2016-04-01 18:21
@talpasco I have had a couple people try to reproduce and I am pretty sure the example is working fine. I am going to close the issue.

Please feel free to carry on the discussion and mention me directly in your comments, I will try to help you get the example running.

**Closed by richardpringle** 2016-04-01 18:21 UTC
Labels: triage, waiting

**Comment by talpasco** [comment] 2016-04-04 08:53
Thanks for all the effort & sorry for the hassle.
I was using Visual Studio, and it was updating all of the packages to the latest version, in this case "user.afterRemote('create, ...)" wasn't firing.
When I decided to start from scratch, it was running smooth. I suspect that one of the up-to-date packages is causing this issue.
I'm on a tight schedule, so I'll investigate it next week and provide some answers.

Ones again, Thank you very much,
Tal

**Comment by DaGaMs** [comment] 2016-04-29 11:10
I have debugged this extensively right now. I started with this example repo straight out of Github, and it indeed calls `afterRemote` just fine. I then proceeded to update all dependencies the newest loopback version. It still works fine. I then changed all the code to resemble the default "out of the box" loopback app after `slc loopback`. After a lot of back and forth, I traced it down to [one simple line of code](https://github.com/strongloop/loopback-example-user-management/blob/master/server/model-config.json#L12):

```
  "User": {
    "dataSource": "db",
    "public": false
  },
```

in [model-config.json](https://github.com/strongloop/loopback-example-user-management/blob/master/server/model-config.json). In a default loopback app, the `"public": false` is **missing**. Hence, the POST is routed to the built-in model's remote methods. Hope that helps some people...

**Comment by superkhau** [comment] 2016-04-29 23:10
>In a default loopback app, the "public": false is missing. Hence, the POST is routed to the built-in model's remote methods. Hope that helps some people...

User model by default is public as it provides `sign up` and `login`, etc

**Comment by superkhau** [comment] 2016-04-29 23:11
@DaGaMs If you are running into a specific issue now, please open up a new issue as we do not usually check closed issues.

**Comment by DaGaMs** [comment] 2016-04-30 09:03
@superkhau I left the above comment here for others, since I ran into problems when trying to follow the tutorial and I think it's a common trap. `User` should indeed be public _iff_ you don't have your own custom `user` subclass - if you created a `user` model that inherits from `User`, you have to make `User` private, otherwise there's a namespace issue with the route. Of course, the best thing to do would be to just not name your custom user class `user`, but something else like `webuser`...

**Comment by superkhau** [comment] 2016-05-01 00:44
@DaGaMs Would you like to submit a PR to the README instead to make it more noticeable for people who are following the tutorial like you did?

>Of course, the best thing to do would be to just not name your custom user class user, but something else like webuser...

We definitely need to change this since it always causes confusion. ;)
